pipeline {
    agent any
    stages {
        stage('Example Build') {
            steps {
                echo 'Hello World!'
            }
        }
        stage('Example Deploy') {
            when {
                beforeAgent true
                beforeInput true
                beforeOptions true
                triggeredBy "TimerTrigger"
                not { branch 'master' }
                //expression { BRANCH_NAME ==~ /(production|staging)/ }
                //anyOf {
                //    environment name: 'DEPLOY_TO', value: 'production'
                //    environment name: 'DEPLOY_TO', value: 'staging'
                //}
            }
            input {
                message "Deploy to production?"
                id "simple-input"
            }
            options {
                lock label: 'testing-deploy-envs', quantity: 1, variable: 'deployEnv'
            }
            steps {
                echo 'Deploying'
            }
        }
    }
}
