pipeline {
    agent any
    stages {
        stage('Example Build') {
            steps {
                echo "Hello World! ${env.BRANCH_NAME}"
            }
        }
        stage('Example Deploy') {
            when {
                expression { env.BRANCH_NAME ==~ /(main|production|staging)/ }
                anyOf {
                    environment name: 'DEPLOY_TO', value: 'main'
                    environment name: 'DEPLOY_TO', value: 'production'
                    environment name: 'DEPLOY_TO', value: 'staging'
                }
            }
            steps {
                echo 'Deploying'
            }
        }
    }
}
