pipeline {
    agent any
    stages {
        //Sequential Examples
        stage('Non-Sequential Stage') {
            //agent {
            //    label 'for-non-sequential'
            //}
            steps {
                echo "On Non-Sequential Stage"
            }
        }
        stage('Sequential') {
            //agent {
            //    label 'for-sequential'
            //}
            environment {
                FOR_SEQUENTIAL = "some-value"
            }
            stages {
                stage('In Sequential 1') {
                    steps {
                        echo "In Sequential 1"
                    }
                }
                stage('In Sequential 2') {
                    steps {
                        echo "In Sequential 2"
                    }
                }
            }
        }
        
        //Parallel Examples
        stage('Parallel Stage') {
            failFast true
            parallel {
                stage('Parallel A') {
                    steps {
                        echo "On Parallel A"
                    }
                }
                stage('Parallel B') {
                    steps {
                        echo "On Parallel B"
                    }
                }
                stage('Parallel C') {
                    stages {
                        stage('Nested Parallel 1') {
                            steps {
                                echo "In stage Nested 1 within Parallel C"
                            }
                        }
                        stage('Nested Parallel 2') {
                            steps {
                                echo "In stage Nested 2 within Parallel C"
                            }
                        }
                    }
                }
            }
        }
    }
}
