pipeline {
    agent any
    triggers {
        cron('H */4 * * 1-5')
      
        //every fifteen minutes (perhaps at :07, :22, :37, :52)
        triggers{ cron('H/15 * * * *') }

        //every ten minutes in the first half of every hour (three times, perhaps at :04, :14, :24)
        triggers{ cron('H(0-29)/10 * * * *') }

        //once every two hours at 45 minutes past the hour starting at 9:45 AM and finishing at 3:45 PM every weekday.
        triggers{ cron('45 9-16/2 * * 1-5') }

        //once in every two hours slot between 9 AM and 5 PM every weekday (perhaps at 10:38 AM, 12:38 PM, 2:38 PM, 4:38 PM)
        triggers{ cron('H H(9-16)/2 * * 1-5') }

        //once a day on the 1st and 15th of every month except December
        triggers{ cron('H H 1,15 1-11 *') }
    }
    stages {
        stage('Example') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
