pipeline {
    agent any
    environment { 
      CC = 'clang'
    }
    stages {
        stage('Example Global Environment') {
            steps {
                sh 'echo "CC is $CC"'
            }
        }
        stage('Example Username with Password') {
            environment {
                SERVICE_CREDS = credentials('kelvin')
            }
            steps {
                sh 'echo "Service user is $SERVICE_CREDS_USR"'
                sh 'echo "Service password is $SERVICE_CREDS_PSW"'
            }
        }
        stage('Example SSH Username with private key') {
            environment {
                SSH_CREDS = credentials('kelvin-key')
            }
            steps {
                sh 'echo "SSH private key is located at $SSH_CREDS"'
                sh 'echo "SSH user is $SSH_CREDS_USR"'
                sh 'echo "SSH passphrase is $SSH_CREDS_PSW"'
            }
        }
    }
}
