pipeline {
    agent any
    options {
        timeout(time: 10, unit: 'SECONDS') 
    }
    stages {
        stage('Example') {
            options { retry(3) }
            steps {
                echo 'Hello World'
            }
        }
    }
}
