pipeline {
    agent any
    stages {
        stage('Post Example') {
            steps {
                echo 'Hello Word!'
            }
        }
        post {
            always {
                echo 'Always RUN'
            }

            cleanup {
                echo 'Run the steps in this post condition after every other post condition has been evaluated, regardless of the Pipeline or stage’s status.'
            }
        }
    }
}
