pipeline {
    agent any
    stages {
        stage('Post Example') {
            steps {
                echo 'Hello Word!'
            }
        }
        post {
            always {
                echo 'Always RUN'
            }
            
        }
    }
}
