pipeline {
    agent any
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '\nOne\nTwo\nThree\n', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    stages {
        stage('Example') {
            steps {
                echo "string - Hello ${params.PERSON}"

                echo "text - Biography: ${params.BIOGRAPHY}"

                echo "booleanParam - Toggle: ${params.TOGGLE}"

                echo "choice - Choice: ${params.CHOICE}"

                echo "password - Password: ${params.PASSWORD}"
            }
        }
    }
}
